[project]
name = "polars-decimal-bug"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "adbc-driver-postgresql>=1.8.0",
    "polars>=1.33.1",
    "pyarrow>=15.0.0",
]
